name: 03 - Actions

on: 
  push:
    branches: 
      - "feature/**"

jobs:
  checkout_java_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'

      - name: Compilar projeto com Maven
        run: mvn clean package -DskipTests

      - name: Verificar conteúdo gerado
        run: ls -la target

      - name: Build da imagem Docker
        run: docker build -t coleta-app .
